[package]
name = "gemm-f16"
version = "0.15.5"
edition = "2021"
authors = ["sarah <>"]
description = "Playground for matrix multiplication algorithms"
readme = "../README.md"
repository = "https://github.com/sarah-ek/gemm/"
license = "MIT"
keywords = ["linear-algebra"]

[dependencies]
lazy_static = { workspace = true }
raw-cpuid = { workspace = true }
seq-macro = { workspace = true }
dyn-stack = { workspace = true }
num-traits = { workspace = true }
num-complex = { workspace = true }
rayon = { workspace = true }
paste = { workspace = true }

gemm-common = { version = "0.15", path = "../gemm-common" }
gemm-f32 = { version = "0.15", path = "../gemm-f32" }
half = { workspace = true }

[features]
default = ["std"]
std = []
nightly = ["gemm-common/nightly"]
